/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FxyContainer {
        /**
          * Sets the `place-content` value for aligning content within the container. Accepts a combination of `justify-content` and `align-content` values. Example: "center space-around".
         */
        "fxyAlign": string;
        /**
          * Sets the align-items property of the container. Aligns items along the cross axis.
         */
        "fxyAlignItems": 'flex-start' | 'flex-end' | 'center' | 'baseline' | 'stretch';
        /**
          * Sets the flex-direction of the container.  Can be "row", "row-reverse", "column", or "column-reverse".
         */
        "fxyDirection": 'row' | 'row-reverse' | 'column' | 'column-reverse';
        /**
          * If `true`, the container will fill its parent's height and width.
         */
        "fxyFill": boolean;
        /**
          * Sets spacing between immediate child elements (`fxy-item`). The value is applied as a right margin to all children except the last one.
         */
        "fxyGap": string;
        /**
          * Sets the flex-wrap property of the container. Can be "nowrap", "wrap", or "wrap-reverse".
         */
        "fxyWrap": 'nowrap' | 'wrap' | 'wrap-reverse' | '';
    }
    interface FxyItem {
        /**
          * A shorthand for setting flex-grow, flex-shrink, and flex-basis. Accepts standard CSS flex property values.
         */
        "fxy": string;
        /**
          * Align self. Allows the default alignment (or the one specified by align-items) to be overridden for individual flex items.
         */
        "fxyAlign": 'auto' | 'flex-start' | 'flex-end' | 'center' | 'baseline' | 'stretch' | '';
    }
}
declare global {
    interface HTMLFxyContainerElement extends Components.FxyContainer, HTMLStencilElement {
    }
    var HTMLFxyContainerElement: {
        prototype: HTMLFxyContainerElement;
        new (): HTMLFxyContainerElement;
    };
    interface HTMLFxyItemElement extends Components.FxyItem, HTMLStencilElement {
    }
    var HTMLFxyItemElement: {
        prototype: HTMLFxyItemElement;
        new (): HTMLFxyItemElement;
    };
    interface HTMLElementTagNameMap {
        "fxy-container": HTMLFxyContainerElement;
        "fxy-item": HTMLFxyItemElement;
    }
}
declare namespace LocalJSX {
    interface FxyContainer {
        /**
          * Sets the `place-content` value for aligning content within the container. Accepts a combination of `justify-content` and `align-content` values. Example: "center space-around".
         */
        "fxyAlign"?: string;
        /**
          * Sets the align-items property of the container. Aligns items along the cross axis.
         */
        "fxyAlignItems"?: 'flex-start' | 'flex-end' | 'center' | 'baseline' | 'stretch';
        /**
          * Sets the flex-direction of the container.  Can be "row", "row-reverse", "column", or "column-reverse".
         */
        "fxyDirection"?: 'row' | 'row-reverse' | 'column' | 'column-reverse';
        /**
          * If `true`, the container will fill its parent's height and width.
         */
        "fxyFill"?: boolean;
        /**
          * Sets spacing between immediate child elements (`fxy-item`). The value is applied as a right margin to all children except the last one.
         */
        "fxyGap"?: string;
        /**
          * Sets the flex-wrap property of the container. Can be "nowrap", "wrap", or "wrap-reverse".
         */
        "fxyWrap"?: 'nowrap' | 'wrap' | 'wrap-reverse' | '';
    }
    interface FxyItem {
        /**
          * A shorthand for setting flex-grow, flex-shrink, and flex-basis. Accepts standard CSS flex property values.
         */
        "fxy"?: string;
        /**
          * Align self. Allows the default alignment (or the one specified by align-items) to be overridden for individual flex items.
         */
        "fxyAlign"?: 'auto' | 'flex-start' | 'flex-end' | 'center' | 'baseline' | 'stretch' | '';
    }
    interface IntrinsicElements {
        "fxy-container": FxyContainer;
        "fxy-item": FxyItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fxy-container": LocalJSX.FxyContainer & JSXBase.HTMLAttributes<HTMLFxyContainerElement>;
            "fxy-item": LocalJSX.FxyItem & JSXBase.HTMLAttributes<HTMLFxyItemElement>;
        }
    }
}
